template:
  default: &default
    base_branch: develop
    labels: bug
    assignees:
      - Ahontic
    reviewers:
      - Volosh1n
    description_main_body: Changes
    push: true
    open: true
  backend:
      <<: *default
      reviewers:
        - some
        - backend
        - developers
  frontend:
    <<: *default
    # reviewers:
    #   - some
    #   - backend
    #   - developers
