template:
  default: &default
    base_branch: develop
    labels:
      - needs review
      - another label
    assignees:
      - Ahontic
    reviewers:
      - Ahontic
    description_main_body: Changes
    jira_base_url: https://sample.atlassian.net/browse/
    push: true
    open: true
  backend:
      <<: *default
      reviewers:
        - some
        - backend
        - developers
  frontend:
    <<: *default
    reviewers:
      - some
      - backend
      - developers
