Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*
    - lib/tasks/*
    - db/**/*
Metrics/ModuleLength:
  Exclude:
    - spec/**/*
Metrics:
  Exclude:
    - bin/**/*
Style/ClassAndModuleChildren:
  Exclude:
    - app/controllers/customers/*
    - app/helpers/**/*
Naming/FileName:
  Exclude:
    - config/initializers/*
