Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*
    - lib/tasks/*
Metrics/ModuleLength:
  Exclude:
    - spec/**/*
Metrics:
  Exclude:
    - bin/**/*
